# Generated by Django 4.1.1 on 2023-03-17 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('upper_catalog', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdirectories', to='shop.catalog', verbose_name='upper catalog')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
                'unique_together': {('title', 'upper_catalog')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('image', models.ImageField(default='products/images/default.jpg', upload_to='products/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png'), message="Can only be saved in 'jpg' or 'png' format")], verbose_name='image')),
                ('specification', models.FileField(blank=True, default=None, null=True, upload_to='products/specifications', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',), message="Can only be saved in 'pdf' format")], verbose_name='specification')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.catalog', verbose_name='catalog')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('slug', models.SlugField(default='', max_length=100, verbose_name='slug')),
                ('products', models.ManyToManyField(related_name='promotions', to='shop.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
    ]
